import type { CSSProperties } from "react";

const card = (accepted: boolean): CSSProperties => ({
  display: "flex",
  flexDirection: "column",
  gap: 12,
  padding: 16,
  marginBottom: 12,
  borderRadius: 10,
  border: `1px solid ${accepted ? "var(--ok)" : "var(--border)"}`,
  background: accepted ? "var(--ok-bg, var(--bg-hover))" : "var(--bg-surface)",
  transition: "border-color 0.12s ease, background 0.12s ease",
});

export const s = {
  card,
  headerRow: { display: "flex", alignItems: "flex-start", gap: 10 } as CSSProperties,
  category: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    fontSize: 11.5,
    fontWeight: 600,
    textTransform: "uppercase" as const,
    letterSpacing: "0.04em",
    color: "var(--text-muted)",
  } as CSSProperties,
  rule: { flex: 1, fontSize: 14, fontWeight: 600, lineHeight: 1.4 } as CSSProperties,
  ruleEdit: {
    width: "100%",
    padding: "8px 10px",
    borderRadius: 8,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    fontSize: 14,
    fontWeight: 600,
    lineHeight: 1.4,
    outline: "none",
    resize: "vertical" as const,
  } as CSSProperties,
  evidence: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: 12,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } as CSSProperties,
  evidencePath: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    color: "var(--text-muted)",
  } as CSSProperties,
  snippet: {
    margin: 0,
    fontFamily: "var(--font-mono)",
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    whiteSpace: "pre-wrap" as const,
    wordBreak: "break-word" as const,
    overflowX: "auto" as const,
  } as CSSProperties,
  confRow: { display: "flex", flexDirection: "column", gap: 6 } as CSSProperties,
  confLabelRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    fontSize: 12,
    color: "var(--text-muted)",
  } as CSSProperties,
  confValue: (color: string): CSSProperties => ({
    fontWeight: 700,
    color,
    fontVariantNumeric: "tabular-nums",
  }),
  actions: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" as const } as CSSProperties,
  editRow: { display: "flex", alignItems: "center", gap: 8 } as CSSProperties,
  spacer: { flex: 1 } as CSSProperties,
};
