import type { CSSProperties } from "react";

export const s = {
  bar: { position: "relative", display: "inline-flex" } satisfies CSSProperties,
  panel: {
    position: "fixed",
    width: 380,
    maxHeight: 360,
    overflowY: "auto",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-strong)",
    borderRadius: 10,
    boxShadow: "var(--shadow-modal)",
    padding: 8,
    zIndex: 50,
    animation: "ddpop .12s ease",
    cursor: "default",
  } satisfies CSSProperties,
  panelHeader: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    padding: "4px 6px 8px",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  rows: { display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  row: (hover: boolean): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    gap: 5,
    width: "100%",
    textAlign: "left",
    padding: "9px 10px",
    border: "none",
    borderRadius: 8,
    background: hover ? "var(--bg-hover)" : "transparent",
    cursor: "pointer",
  }),
  rowTitleLine: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  rowTitle: {
    fontSize: 13.5,
    fontWeight: 650,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  rowMeta: { display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  rowFile: { fontSize: 12.5, color: "var(--accent-text)" } satisfies CSSProperties,
  rowSnippet: {
    fontSize: 12.5,
    lineHeight: 1.45,
    color: "var(--text-secondary)",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  } satisfies CSSProperties,
  empty: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "16px 0",
    fontSize: 13,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
} as const;
